Update build-kernel.yml

diff --git a/.github/workflows/build-kernel.yml b/.github/workflows/build-kernel.yml
--- a/.github/workflows/build-kernel.yml
+++ b/.github/workflows/build-kernel.yml
@@ -1,6 +1,5 @@
 name: Build Kernel
 on:
-
   workflow_dispatch:
 
 jobs:
@@ -9,26 +8,31 @@ jobs:
     runs-on: ubuntu-latest
     steps:
     - uses: actions/checkout@v3
+
     - name: Setup Configuration
       run: |
-        echo "KERNEL_SOURCE=$(cat config.env | grep "KERNEL_SOURCE" | head -n 1 | cut -d "=" -f 2)" >> $GITHUB_ENV
-        echo "KERNEL_SOURCE_BRANCH=$(cat config.env | grep "KERNEL_SOURCE_BRANCH" | head -n 1 | cut -d "=" -f 2)" >> $GITHUB_ENV
-        echo "KERNEL_DEFCONFIG=$(cat config.env | grep "KERNEL_DEFCONFIG" | head -n 1 | cut -d "=" -f 2)" >> $GITHUB_ENV
-        echo "TARGET_ARCH=$(cat config.env | grep "TARGET_ARCH" | head -n 1 | cut -d "=" -f 2)" >> $GITHUB_ENV
-        echo "KERNEL_FILE=$(cat config.env | grep "KERNEL_FILE" | head -n 1 | cut -d "=" -f 2)" >> $GITHUB_ENV
-        echo "CLANG_VERSION=$(cat config.env | grep "CLANG_VERSION" | head -n 1 | cut -d "=" -f 2)" >> $GITHUB_ENV
-        echo "BUILD_EXTRA_COMMAND=$(cat config.env | grep "EXTRA_BUILD_COMMAND" | head -n 1 | cut -d ":" -f 2)" >> $GITHUB_ENV
-        echo "USE_KERNELSU=$(cat config.env | grep "USE_KERNELSU" | head -n 1 | cut -d "=" -f 2)" >> $GITHUB_ENV
-        echo "MAKE_BOOT_IMAGE=$(cat config.env | grep "MAKE_BOOT_IMAGE" | head -n 1 | cut -d "=" -f 2)" >> $GITHUB_ENV
-        echo "BOOT_SIGNATURE=$(cat config.env | grep "MAKE_BOOT_IMAGE" | head -n 1 | cut -d "=" -f 2)" >> $GITHUB_ENV
-        echo "SOURCE_BOOT_IMAGE=$(cat config.env | grep "SOURCE_BOOT_IMAGE" | head -n 1 | cut -d "=" -f 2)" >> $GITHUB_ENV
+        echo "KERNEL_SOURCE=$(grep "KERNEL_SOURCE" config.env | cut -d "=" -f 2)" >> $GITHUB_ENV
+        echo "KERNEL_SOURCE_BRANCH=$(grep "KERNEL_SOURCE_BRANCH" config.env | cut -d "=" -f 2)" >> $GITHUB_ENV
+        echo "KERNEL_DEFCONFIG=$(grep "KERNEL_DEFCONFIG" config.env | cut -d "=" -f 2)" >> $GITHUB_ENV
+        echo "TARGET_ARCH=$(grep "TARGET_ARCH" config.env | cut -d "=" -f 2)" >> $GITHUB_ENV
+        echo "KERNEL_FILE=$(grep "KERNEL_FILE" config.env | cut -d "=" -f 2)" >> $GITHUB_ENV
+        echo "CLANG_VERSION=$(grep "CLANG_VERSION" config.env | cut -d "=" -f 2)" >> $GITHUB_ENV
+        echo "BUILD_EXTRA_COMMAND=$(grep "EXTRA_BUILD_COMMAND" config.env | cut -d "=" -f 2)" >> $GITHUB_ENV
+        echo "USE_KERNELSU=$(grep "USE_KERNELSU" config.env | cut -d "=" -f 2)" >> $GITHUB_ENV
+        echo "MAKE_BOOT_IMAGE=$(grep "MAKE_BOOT_IMAGE" config.env | cut -d "=" -f 2)" >> $GITHUB_ENV
+        echo "BOOT_SIGNATURE=$(grep "BOOT_SIGNATURE" config.env | cut -d "=" -f 2)" >> $GITHUB_ENV
+        echo "SOURCE_BOOT_IMAGE=$(grep "SOURCE_BOOT_IMAGE" config.env | cut -d "=" -f 2)" >> $GITHUB_ENV
 
     - name: Setup build kernel environment
       run: |
         echo "BUILD_TIME=$(TZ=Asia/Shanghai date "+%Y%m%d%H%M")" >> $GITHUB_ENV
         echo "DEVICE=$(echo ${{ env.KERNEL_DEFCONFIG }} | sed 's!vendor/!!;s/_defconfig//;s/_user//;s/-perf//')" >> $GITHUB_ENV
         sudo apt-get update
-        sudo apt-get install git ccache automake flex lzop bison gperf build-essential zip curl zlib1g-dev g++-multilib libxml2-utils bzip2 libbz2-dev libbz2-1.0 libghc-bzlib-dev squashfs-tools pngcrush schedtool dpkg-dev liblz4-tool make optipng maven libssl-dev pwgen libswitch-perl policycoreutils minicom libxml-sax-base-perl libxml-simple-perl bc libc6-dev-i386 lib32ncurses5-dev libx11-dev lib32z-dev libgl1-mesa-dev xsltproc unzip device-tree-compiler python2 python3 default-jdk
+        sudo apt-get install -y git ccache automake flex lzop bison gperf build-essential zip curl zlib1g-dev \
+        g++-multilib libxml2-utils bzip2 libbz2-dev libghc-bzlib-dev squashfs-tools pngcrush schedtool dpkg-dev \
+        liblz4-tool make optipng maven libssl-dev pwgen libswitch-perl policycoreutils minicom \
+        libxml-sax-base-perl libxml-simple-perl bc libc6-dev-i386 lib32ncurses5-dev libx11-dev lib32z-dev \
+        libgl1-mesa-dev xsltproc unzip device-tree-compiler python2 python3 default-jdk
         mkdir -p $GITHUB_WORKSPACE/kernel_workspace
 
     - name: Download Clang-aosp Gcc-aosp Gcc32-aosp
@@ -65,12 +69,13 @@ jobs:
       if: env.MAKE_BOOT_IMAGE == 'true'
       run: |
         cd $GITHUB_WORKSPACE/kernel_workspace
-        wget -O boot-source.img ${{ env.SOURCE_BOOT_IMAGE }}
+        wget -O boot-source.img "${{ env.SOURCE_BOOT_IMAGE }}"
         if [ -f boot-source.img ]; then
-            echo "FORMAT_MKBOOTING=$(echo `tools/unpack_bootimg.py --boot_img=boot-source.img --format mkbootimg`)" >> $GITHUB_ENV
+            echo "FORMAT_MKBOOTING=$(tools/unpack_bootimg.py --boot_img=boot-source.img --format mkbootimg)" >> $GITHUB_ENV
             echo "HAVE_SOURCE_BOOT_IMAGE=true" >> $GITHUB_ENV
         else
-            echo "Source boot image is empty"
+            echo "Source boot image download failed"
+            exit 1
         fi
 
     - name: Setup KernelSU
@@ -83,59 +88,68 @@ jobs:
     - name: Build kernel
       run: |
         cd $GITHUB_WORKSPACE/kernel_workspace/android-kernel
-        export PATH=$GITHUB_WORKSPACE/kernel_workspace/clang-aosp/bin:$PATH
-        export KBUILD_BUILD_HOST=Github-Action
-        export KBUILD_BUILD_USER=$(echo ${{ github.actor }} | tr A-Z a-z)
-        make -j$(nproc --all) O=out ARCH=${{ env.TARGET_ARCH }} CLANG_TRIPLE=aarch64-linux-gnu- CROSS_COMPILE=$GITHUB_WORKSPACE/kernel_workspace/gcc-aosp/bin/aarch64-linux-android- CROSS_COMPILE_ARM32=$GITHUB_WORKSPACE/kernel_workspace/gcc32-aosp/bin/arm-linux-androideabi- CROSS_COMPILE_COMPAT=$GITHUB_WORKSPACE/kernel_workspace/gcc32-aosp/bin/arm-linux-androideabi- CC=clang ${{ env.BUILD_EXTRA_COMMAND }} ${{ env.KERNEL_DEFCONFIG }}
-        make -j$(nproc --all) O=out ARCH=${{ env.TARGET_ARCH }} CLANG_TRIPLE=aarch64-linux-gnu- CROSS_COMPILE=$GITHUB_WORKSPACE/kernel_workspace/gcc-aosp/bin/aarch64-linux-android- CROSS_COMPILE_ARM32=$GITHUB_WORKSPACE/kernel_workspace/gcc32-aosp/bin/arm-linux-androideabi- CROSS_COMPILE_COMPAT=$GITHUB_WORKSPACE/kernel_workspace/gcc32-aosp/bin/arm-linux-androideabi- CC=clang ${{ env.BUILD_EXTRA_COMMAND }}
+        export PATH="$GITHUB_WORKSPACE/kernel_workspace/clang-aosp/bin:$PATH"
+        export KBUILD_BUILD_HOST="Github-Action"
+        export KBUILD_BUILD_USER="${{ github.actor }}"
+        make -j$(nproc --all) O=out ARCH=${{ env.TARGET_ARCH }} \
+        CLANG_TRIPLE=aarch64-linux-gnu- \
+        CROSS_COMPILE=$GITHUB_WORKSPACE/kernel_workspace/gcc-aosp/bin/aarch64-linux-android- \
+        CROSS_COMPILE_ARM32=$GITHUB_WORKSPACE/kernel_workspace/gcc32-aosp/bin/arm-linux-androideabi- \
+        CC=clang ${{ env.BUILD_EXTRA_COMMAND }} ${{ env.KERNEL_DEFCONFIG }}
+        
+        make -j$(nproc --all) O=out ARCH=${{ env.TARGET_ARCH }} \
+        CLANG_TRIPLE=aarch64-linux-gnu- \
+        CROSS_COMPILE=$GITHUB_WORKSPACE/kernel_workspace/gcc-aosp/bin/aarch64-linux-android- \
+        CROSS_COMPILE_ARM32=$GITHUB_WORKSPACE/kernel_workspace/gcc32-aosp/bin/arm-linux-androideabi- \
+        CC=clang ${{ env.BUILD_EXTRA_COMMAND }}
 
     - name: Make boot image
       if: env.HAVE_SOURCE_BOOT_IMAGE == 'true'
       run: |
         cd $GITHUB_WORKSPACE/kernel_workspace
-        tools/unpack_bootimg.py --boot_img boot-source.img
+        mkdir -p out
+        tools/unpack_bootimg.py --boot_img boot-source.img --out out
         cp android-kernel/out/arch/${{ env.TARGET_ARCH }}/boot/${{ env.KERNEL_FILE }} out/kernel
         tools/mkbootimg.py ${{ env.FORMAT_MKBOOTING }} -o boot_unsign.img
-        if [ -f boot_unsign.img ]; then
-            echo "MAKE_BOOT_IMAGE_IS_OK=true" >> $GITHUB_ENV
-        else
-            echo "Boot image is empty"
-        fi
-        tools/mkbootimg.py --header_version 0 --os_version 13.0.0 --os_patch_level 2023-01 --kernel out/kernel --ramdisk out/ramdisk --pagesize 0x00001000 --base 0x00000000 --kernel_offset 0x00008000 --ramdisk_offset 0x00000000 --second_offset 0x00000000 --tags_offset 0x00000100 --board '' --cmdline 'androidboot.hardware=qcom user_debug=31 msm_rtb.filter=0x37 ehci-hcd.park=3 lpm_levels.sleep_disabled=1 sched_enable_hmp=1 sched_enable_power_aware=1 service_locator.enable=1 swiotlb=2048 androidboot.usbconfigfs=true androidboot.usbcontroller=a800000.dwc3 androidboot.selinux=permissive loop.max_part=7 buildvariant=userdebug veritykeyid=id:7e4333f9bba00adfe0ede979e28ed1920492b40f' -o bootp_unsign.img
-        if [ -f bootp_unsign.img ]; then
-            echo "MAKE_BOOTP_IMAGE_IS_OK=true" >> $GITHUB_ENV
-        else
-            echo "Bootp image is empty"
-        fi
+        [ -f boot_unsign.img ] && echo "MAKE_BOOT_IMAGE_IS_OK=true" >> $GITHUB_ENV
+
+        # Create permissive boot image
+        tools/mkbootimg.py \
+        --header_version 0 \
+        --os_version 13.0.0 \
+        --os_patch_level 2023-01 \
+        --kernel out/kernel \
+        --ramdisk out/ramdisk \
+        --pagesize 0x00001000 \
+        --base 0x00000000 \
+        --kernel_offset 0x00008000 \
+        --ramdisk_offset 0x00000000 \
+        --second_offset 0x00000000 \
+        --tags_offset 0x00000100 \
+        --board '' \
+        --cmdline 'androidboot.hardware=qcom user_debug=31 msm_rtb.filter=0x37 ehci-hcd.park=3 lpm_levels.sleep_disabled=1 sched_enable_hmp=1 sched_enable_power_aware=1 service_locator.enable=1 swiotlb=2048 androidboot.usbconfigfs=true androidboot.usbcontroller=a800000.dwc3 androidboot.selinux=permissive loop.max_part=7 buildvariant=userdebug veritykeyid=id:7e4333f9bba00adfe0ede979e28ed1920492b40f' \
+        -o bootp_unsign.img
+        [ -f bootp_unsign.img ] && echo "MAKE_BOOTP_IMAGE_IS_OK=true" >> $GITHUB_ENV
 
     - name: Boot Signature
       if: env.BOOT_SIGNATURE == 'true'
       run: |
         cd $GITHUB_WORKSPACE/kernel_workspace
         java -jar bootsigner/boot_signer.jar /boot boot_unsign.img bootsigner/verity.pk8 bootsigner/verity.x509.pem boot.img
-        RET=$(java -jar bootsigner/boot_signer.jar -verify boot.img 2>&1)
-        if (`echo $RET | grep "VALID" >/dev/null 2>&1`);
-        then
-            echo "Boot Signature is VALID";
-            echo "BOOT_SIGNATURE_VALID=true" >> $GITHUB_ENV
-        else
-            echo "Boot Signature is not VALID";
+        if java -jar bootsigner/boot_signer.jar -verify boot.img | grep -q "VALID"; then
+          echo "BOOT_SIGNATURE_VALID=true" >> $GITHUB_ENV
         fi
+
         java -jar bootsigner/boot_signer.jar /boot bootp_unsign.img bootsigner/verity.pk8 bootsigner/verity.x509.pem boot_permissive.img
-        RET=$(java -jar bootsigner/boot_signer.jar -verify boot.img 2>&1)
-        if (`echo $RET | grep "VALID" >/dev/null 2>&1`);
-        then
-            echo "Boot Signature is VALID";
-            echo "BOOTP_SIGNATURE_VALID=true" >> $GITHUB_ENV
-        else
-            echo "Boot Signature is not VALID";
+        if java -jar bootsigner/boot_signer.jar -verify boot_permissive.img | grep -q "VALID"; then
+          echo "BOOTP_SIGNATURE_VALID=true" >> $GITHUB_ENV
         fi
 
-    - name: Upload boot image with permissive
-      if: env.MAKE_BOOT_IMAGE_IS_OK == 'true' && env.BOOT_SIGNATURE_VALID == 'true' && env.MAKE_BOOTP_IMAGE_IS_OK == 'true' && env.BOOTP_SIGNATURE_VALID == 'true'
-      uses: actions/upload-artifact@v3
+    - name: Upload boot image
+      if: env.MAKE_BOOT_IMAGE_IS_OK == 'true' && env.BOOT_SIGNATURE_VALID == 'true'
+      uses: actions/upload-artifact@v4
       with:
-        name: boot-${{ env.DEVICE }}-${{ env.BUILD_TIME }}
+        name: boot-${{ env.DEVICE }}-${{ env.BUILD_TIME }}${{ env.UPLOADNAME }}
         path: |
-          kernel_workspace/boot_permissive.img
-
+          $GITHUB_WORKSPACE/kernel_workspace/boot.img
+          $GITHUB_WORKSPACE/kernel_workspace/boot_permissive.img
